spring.application.name=payment
server.port=8084
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.mongodb.driver=DEBUG
