spring.application.name=user
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
server.port=8081
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.mongodb.driver=DEBUG
logging.level.jwtcommon.security=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.jwtcommon.security=DEBUG
logging.level.com.ecommerce=DEBUG
